name: CI

on:
  push:
    branches: [ main-aws ]
  pull_request:
    branches: [ main-aws ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      # Frontend (Next.js) のセットアップ・ビルド
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # Backend (Rails) のセットアップ・テスト
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install backend dependencies
        working-directory: backend
        run: bundle install --jobs 4 --retry 3

      - name: Run backend tests
        working-directory: backend
        run: bundle exec rails test

      # Terraform のフォーマットチェック
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Format Check
        working-directory: infrastructure
        run: terraform fmt -check
